# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gof-NxYrsYa_P39CesNuLYsx9C2sSVLI
"""

import random
import time

def math_game():
    """
    Функция реализует математическую игру на сложение случайных чисел.
    При неправильном ответе назначается штрафная пауза, которая увеличивается
    с каждой ошибкой на 1 секунду. Начальная пауза - 3 секунды.
    """
    penalty = 3  # начальная штрафная пауза

    while True:
        # Генерация двух случайных натуральных чисел от 1 до 100
        num1 = random.randint(1, 100)
        num2 = random.randint(1, 100)

        # Вычисление правильной суммы
        correct_sum = num1 + num2

        # Запрос ответа у пользователя
        print(f"Новый пример: {num1} + {num2}?")

        try:
            # Получение ответа от пользователя
            user_answer = int(input())
        except ValueError:
            # Обработка некорректного ввода (не число)
            print(f"Некорректный ввод! Штрафная пауза: {penalty} секунды")
            time.sleep(penalty)
            penalty += 1
            continue

        # Проверка ответа
        if user_answer == correct_sum:
            print("Поздравляю! Ваш ответ правильный")
            break  # Завершение цикла при правильном ответе
        else:
            print(f"Неверно! Штрафная пауза: {penalty} секунды")
            time.sleep(penalty)  # Штрафная пауза
            penalty += 1  # Увеличение штрафной паузы на следующую ошибку